# site settings
title: 공공정책성과평가연구원
subtitle: by HTML5 UP
email: 3pe@3pe.re.kr
description: 국내 최고의 공공부문 성과분석·평가 전문기관<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: 공공정책성과평가연구원
street_address: 방배천로 155 유청빌딩 3층
city: 서초구
state: 서울
zip_code: 06564
country: 대한민국
phone: (02) 6925-0460

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/3pei39

# build settings
markdown: kramdown

sass:
  style: compressed
